### ISSUE TITLE
你好，现在还打算写吗，如果可以的话，可以一起研究哇。

### ISSUE THREAD

**Issue by LittleGuest** [Saturday-morning/origingo#2]

**Comment by 1638410** [comment]
我不会编程，下面是旁观者视角的解说和推荐，我当年无知者无畏哈哈，现在明白连基础都不会，我就知道这么多，不打扰了（

**来加个discord频道（这里有大把会编程的活人（不是**：https://discord.gg/BPWZCpuH

引擎列表：
https://senseis.xmp.net/?GoPrograms
https://online-go.com/docs/other-go-resources

总的来说常见gtp引擎有： （纯靠个人理解和记忆，可能有错误）

连蒙特卡洛搜索都没：gnugo（最经典-其实9路可以开但是性能很差，但是不用mcts依旧能有业余一段，相当强了） amigo（战五渣）
旧时代+加了个模型：**pachi**（教学版本michi） fuego **ray**（还有一个名字有点像的，忘了）
新时代（alphago之后，加粗的就是用了模型的，当然不一定准确，记忆不好）：**minigo** **leelazero**（前身 leela 特色fork **sai**） **phoenixgo**（微信团队整的，炼了一会就没下文了） **ELF-opengo（好像有个elf2，知乎有相关文章好像）**  **sayuri** **katago** 这些

（最经典的就是leelazero和katago了，sayuri也很好）

而gtp界面可以有sabaki lizzieyzy 之类 还有一个katrain，gogui…

在github上有一两个rust语言跟围棋有关系的，https://github.com/search?q=+baduk+language%3ARust&type=repositories&l=Rust



----
https://github.com/yenw/computer-go-dataset
https://github.com/featurecat/go-dataset
https://github.com/aki65/aki65.github.io （围棋引擎 port 到 安卓）
https://github.com/breakwa11/GoAIRatings
